name: Name of the issue template
description: Description of the issue template
labels: ["a list", "of", "labels"] # Labels to apply to the issue
assignees: [] # List of GitHub usernames to assign the issue to
title: "[Demo] - Issue Title"
body:
  - type: markdown
    id: section-id
    attributes:
      label: Section Title
      description: Description of the issue template section
      value: "Description of the issue template section and provide examples"