name: Name of the issue template
description: Description of the issue template
labels: ["a list", "of", "labels"] # Labels to apply to the issue
assignees: [] # List of GitHub usernames to assign the issue to
title: "[Demo] - Issue Title"
body:
  - type: textarea
    id: section-id
    attributes:
      label: Section Title
      description: Description of this section
      placeholder: Provide Example Text Here